=== PreMiD/Activities/schemas/metadata/1.15.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://schemas.premid.app/metadata/1.15",
  "title": "Metadata",
  "type": "object",
  "description": "Metadata that describes a activity.",
  "definitions": {
    "user": {
      "type": "object",
      "description": "User information.",
      "properties": {
        "name": {
          "type": "string",
          "description": "The name of the user."
        },
        "id": {
          "type": "string",
          "description": "The Discord snowflake of the user.",
          "pattern": "^\\d+$"
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "id"
      ]
    }
  },
  "properties": {
    "$schema": {
      "$comment": "This is required otherwise the schema will fail itself when it is applied to a document via $schema. This is optional so that validators that use this schema don't fail if the metadata doesn't have the $schema property.",
      "type": "string",
      "description": "The metadata schema URL."
    },
    "author": {
      "$ref": "#/definitions/user",
      "description": "The author of this activity."
    },
    "contributors": {
      "type": "array",
      "description": "Any extra contributors to this activity.",
      "items": {
        "$ref": "#/definitions/user"
      }
    },
    "service": {
      "type": "string",
      "description": "The service this activity is for."
    },
    "altnames": {
      "type": "array",
      "description": "Alternative names for the service.",
      "items": {
        "type": "string",
        "description": "An alternative name."
      },
      "minItems": 1
    },
    "description": {
      "type": "object",
      "description": "A description of the activity in multiple languages.",
      "propertyNames": {
        "type": "string",
        "description": "The language key. The key must be languagecode(-regioncode).",
        "pattern": "^[a-z]{2,3}(?:-(?:[a-z]{2}|[0-9]{1,3}))?$"
      },
      "patternProperties": {
        "^[a-z]{2,3}(?:-(?:[a-z]{2}|[0-9]{1,3}))?$": {
          "type": "string",
          "description": "The description of the activity in the key's language."
        }
      },
      "additionalProperties": false,
      "required": [
        "en"
      ]
    },
    "url": {
      "type": [
        "string",
        "array"
      ],
      "description": "The service's website URL, or an array of URLs. Protocols should not be added.",
      "pattern": "^(([a-z0-9-]+\\.)*[0-9a-z_-]+(\\.[a-z]+)+|(\\d{1,3}\\.){3}\\d{1,3}|localhost)$",
      "items": {
        "type": "string",
        "description": "One of the service's website URLs.",
        "pattern": "^(([a-z0-9-]+\\.)*[0-9a-z_-]+(\\.[a-z]+)+|(\\d{1,3}\\.){3}\\d{1,3}|localhost)$"
      },
      "minItems": 2
    },
    "version": {
      "type": "string",
      "description": "The SemVer version of the activity. Must just be major.minor.patch.",
      "pattern": "^\\d+\\.\\d+\\.\\d+$"
    },
    "apiVersion": {
      "type": "integer",
      "description": "The Activity System version this activity supports.",
      "minimum": 1,
      "maximum": 2
    },
    "logo": {
      "type": "string",
      "description": "The logo of the service this activity is for.",
      "pattern": "^https?://.+\\.(png|jpe?g|gif|webp)$"
    },
    "thumbnail": {
      "type": "string",
      "description": "A thumbnail of the service this activity is for.",
      "pattern": "^https?://.+\\.(png|jpe?g|gif|webp)$"
    },
    "color": {
      "type": "string",
      "description": "The theme color of the service this activity is for. Must be either a 6 digit or a 3 digit hex code.",
      "pattern": "^#([A-Fa-f0-9]{3}){1,2}$"
    },
    "tags": {
      "type": [
        "array"
      ],
      "description": "The tags for the activity.",
      "items": {
        "type": "string",
        "description": "A tag.",
        "pattern": "^[^A-Z\\s!\"#$%&'()*+,./:;<=>?@\\[\\\\\\]^_`{|}~]+$"
      },
      "minItems": 1
    },
    "category": {
      "type": "string",
      "description": "The category the activity falls under.",
      "enum": [
        "anime",
        "games",
        "music",
        "socials",
        "videos",
        "other"
      ]
    },
    "iframe": {
      "type": "boolean",
      "description": "Whether or not the activity should run in IFrames."
    },
    "readLogs": {
      "type": "boolean",
      "description": "Whether or not the extension should be reading logs."
    },
    "regExp": {
      "type": "string",
      "description": "A regular expression used to match URLs for the activity to inject into."
    },
    "iFrameRegExp": {
      "type": "string",
      "description": "A regular expression used to match IFrames for the activity to inject into."
    },
    "allowURLOverrides": {
      "type": "boolean",
      "description": "Whether or not the activity should allow URL overrides."
    },
    "settings": {
      "type": "array",
      "description": "An array of settings the user can change in the activity.",
      "items": {
        "type": "object",
        "description": "A setting.",
        "properties": {
          "id": {
            "type": "string",
            "description": "The ID of the setting."
          },
          "title": {
            "type": "string",
            "description": "The title of the setting. Required only if `multiLanguage` is disabled."
          },
          "description": {
            "type": "string",
            "description": "The description of the setting. Only applicable if `multiLanguage` is disabled."
          },
          "icon": {
            "type": "string",
            "description": "The icon of the setting. Required only if `multiLanguage` is disabled.",
            "pattern": "^fa([bsdrlt]|([-](brands|solid|duotone|regular|light|thin))) fa-[0-9a-z-]+$"
          },
          "if": {
            "type": "object",
            "description": "Restrict showing this setting if another setting is the defined value.",
            "propertyNames": {
              "type": "string",
              "description": "The ID of the setting."
            },
            "patternProperties": {
              "": {
                "type": [
                  "string",
                  "number",
                  "boolean"
                ],
                "description": "The value of the setting."
              }
            },
            "additionalProperties": false
          },
          "placeholder": {
            "type": "string",
            "description": "The placeholder for settings that require input. Shown when the input is empty."
          },
          "value": {
            "type": [
              "string",
              "number",
              "boolean"
            ],
            "description": "The default value of the setting. Not compatible with `values`."
          },
          "values": {
            "type": "array",
            "description": "The default values of the setting. Not compatible with `value`.",
            "items": {
              "type": [
                "string",
                "number",
                "boolean"
              ],
              "description": "The value of the setting."
            }
          },
          "multiLanguage": {
            "type": "boolean",
            "description": "When true, strings from the `general.json` file are available for use, plus the <service>.json file. False is not allowed."
          }
        },
        "additionalProperties": false
      }
    },
    "mobile": {
      "type": "boolean",
      "description": "Whether or not the activity has support for mobile devices."
    }
  },
  "additionalProperties": false,
  "required": [
    "author",
    "service",
    "description",
    "url",
    "version",
    "apiVersion",
    "logo",
    "thumbnail",
    "color",
    "tags",
    "category"
  ]
}

=== PreMiD/Activities/websites/E/Emby/metadata.json
{
  "$schema": "https://schemas.premid.app/metadata/1.16",
  "apiVersion": 1,
  "author": {
    "name": "PreMiD",
    "id": "503557087041683458"
  },
  "contributors": [
    {
      "name": "Bas950",
      "id": "241278257335500811"
    },
    {
      "name": "alexbcberio",
      "id": "202915432175239169"
    }
  ],
  "service": "Emby",
  "description": {
    "en": "Your personal media on any device. Bringing all of your home videos, music, and photos together into one place has never been easier. Your personal Emby Server automatically converts and streams your media on-the-fly to play on any device.",
    "nl": "Uw persoonlijke media op elk apparaat. Het was nog nooit zo eenvoudig om al uw video's, muziek en foto's samen te brengen op één plek. Uw persoonlijke Emby-server converteert en streamt uw media automatisch om ze op elk apparaat af te spelen."
  },
  "url": [
    "emby.media",
    "app.emby.media"
  ],
  "regExp": "^https?[:][/][/].*[/]web[/]index[.]html[/]",
  "version": "1.7.2",
  "logo": "https://cdn.rcd.gg/PreMiD/websites/E/Emby/assets/logo.png",
  "thumbnail": "https://cdn.rcd.gg/PreMiD/websites/E/Emby/assets/thumbnail.png",
  "color": "#52B54B",
  "category": "videos",
  "tags": [
    "video",
    "movie",
    "tv",
    "media"
  ],
  "settings": [
    {
      "id": "showMediaTimestamps",
      "title": "Show media timestamps",
      "icon": "fad fa-play",
      "value": true
    },
    {
      "id": "showTimestamps",
      "title": "Show timestamps",
      "icon": "fad fa-stopwatch",
      "value": true
    },
    {
      "id": "showThumbnails",
      "title": "Show thumbnails",
      "icon": "fad fa-image",
      "value": true
    },
    {
      "id": "audDetail",
      "title": "Audio Details row1",
      "icon": "fas fa-comment-alt-edit",
      "value": "Listening to: %title%",
      "placeholder": "Use %title%, %artist%, %albumartist%, %releasedate%, {0}"
    },
    {
      "id": "audState",
      "title": "Audio Details row2",
      "icon": "fas fa-comment-alt-edit",
      "value": "By: %artist%",
      "placeholder": "Use %title%, %artist%, %albumartist%, %releasedate%, {0}"
    }
  ],
  "allowURLOverrides": true
}

=== PreMiD/Activities/websites/J/Jellyfin/metadata.json
{
  "$schema": "https://schemas.premid.app/metadata/1.16",
  "apiVersion": 1,
  "author": {
    "name": "hashking710",
    "id": "608311692644057088"
  },
  "contributors": [
    {
      "name": "alexbcberio",
      "id": "202915432175239169"
    },
    {
      "name": "Bas950",
      "id": "241278257335500811"
    }
  ],
  "service": "Jellyfin",
  "description": {
    "en": "The Free Software Media System",
    "nl": "Het gratis software mediasysteem"
  },
  "url": "jellyfin.org",
  "regExp": "^https?[:][/][/](jellyfin[.]org|.*[/]web[/](index[.]html)?#)[/]",
  "version": "1.11.0",
  "logo": "https://cdn.rcd.gg/PreMiD/websites/J/Jellyfin/assets/logo.png",
  "thumbnail": "https://cdn.rcd.gg/PreMiD/websites/J/Jellyfin/assets/thumbnail.png",
  "color": "#00698c",
  "category": "videos",
  "tags": [
    "video",
    "movie",
    "tv",
    "media",
    "music"
  ],
  "settings": [
    {
      "id": "lang",
      "multiLanguage": true
    },
    {
      "id": "privacy",
      "title": "Privacy Mode",
      "icon": "fad fa-user-secret",
      "value": false
    },
    {
      "id": "usePresenceName",
      "title": "Show Title as Presence",
      "icon": "fad fa-user-edit",
      "value": true,
      "if": {
        "privacy": false
      }
    },
    {
      "id": "showBrowsingStatus",
      "title": "Show Browsing Status",
      "icon": "fad fa-book-reader",
      "value": true
    },
    {
      "id": "showCover",
      "title": "Show Cover Art",
      "icon": "fas fa-images",
      "value": true,
      "if": {
        "privacy": false
      }
    },
    {
      "id": "showMovies",
      "title": "Show Movies",
      "icon": "fad fa-camera-movie",
      "value": true
    },
    {
      "id": "showSeries",
      "title": "Show Series",
      "icon": "fad fa-film",
      "value": true
    },
    {
      "id": "showMusic",
      "title": "Show Music",
      "icon": "fad fa-music",
      "value": true
    },
    {
      "id": "showSmallImages",
      "title": "Show Small Images",
      "icon": "fad fa-pause",
      "value": true
    },
    {
      "id": "showMediaTimestamps",
      "title": "Show Media Timestamps",
      "icon": "fad fa-play",
      "value": true,
      "if": {
        "privacy": false
      }
    },
    {
      "id": "showTimestamps",
      "title": "Show Elapsed Time",
      "icon": "fad fa-stopwatch",
      "value": true
    },
    {
      "id": "localImageExtraction",
      "title": "Force Local Image Extraction",
      "icon": "fad fa-download",
      "value": false,
      "if": {
        "showCover": true
      }
    }
  ],
  "allowURLOverrides": true
}
